#!/bin/bash
# Deploy Blue-Green strategy

echo "Applying Blue Deployment..."
kubectl apply -f blue_deployment.yaml

echo "Applying Green Deployment..."
kubectl apply -f green_deployment.yaml

echo "Applying Service..."
kubectl apply -f kubeservice.yaml

echo "Checking all deployments..."
kubectl get deployments

echo "Checking all pods..."
kubectl get pods

echo "Checking logs for Green Deployment..."
GREEN_POD=$(kubectl get pods -l version=green -o jsonpath="{.items[0].metadata.name}")
kubectl logs $GREEN_POD
